/* V1 — Create logical schemas */
IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name = 'PORTAL') EXEC('CREATE SCHEMA PORTAL');
IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name = 'BRONZE') EXEC('CREATE SCHEMA BRONZE');
IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name = 'SILVER') EXEC('CREATE SCHEMA SILVER');
IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name = 'GOLD') EXEC('CREATE SCHEMA GOLD');
IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name = 'REPORTING') EXEC('CREATE SCHEMA REPORTING');
IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name = 'WORK') EXEC('CREATE SCHEMA WORK');

