/* V3.1 — Additional core tables in PORTAL schema */

/* PROFILE_DOMAINS */
IF OBJECT_ID('PORTAL.PROFILE_DOMAINS','U') IS NULL
BEGIN
  CREATE TABLE PORTAL.PROFILE_DOMAINS (
    id INT IDENTITY(1,1) PRIMARY KEY,
    profile_code NVARCHAR(50) UNIQUE NOT NULL,
    description NVARCHAR(255) NULL,
    ext_attributes NVARCHAR(MAX) NULL,
    created_by NVARCHAR(255) NOT NULL CONSTRAINT DF_PORTAL_PROFILE_DOMAINS_created_by DEFAULT('MANUAL'),
    created_at DATETIME2 NOT NULL CONSTRAINT DF_PORTAL_PROFILE_DOMAINS_created_at DEFAULT SYSUTCDATETIME(),
    updated_at DATETIME2 NOT NULL CONSTRAINT DF_PORTAL_PROFILE_DOMAINS_updated_at DEFAULT SYSUTCDATETIME()
  );
END;

/* SECTION_ACCESS */
IF OBJECT_ID('PORTAL.SECTION_ACCESS','U') IS NULL
BEGIN
  CREATE TABLE PORTAL.SECTION_ACCESS (
    id INT IDENTITY(1,1) PRIMARY KEY,
    tenant_id NVARCHAR(50) NOT NULL,
    section_code NVARCHAR(50) NULL,
    profile_code NVARCHAR(50) NULL,
    user_id NVARCHAR(50) NULL,
    is_enabled BIT NULL,
    valid_from DATETIME2 NULL,
    valid_to DATETIME2 NULL,
    ext_attributes NVARCHAR(MAX) NULL,
    created_by NVARCHAR(255) NOT NULL CONSTRAINT DF_PORTAL_SECTION_ACCESS_created_by DEFAULT('MANUAL'),
    created_at DATETIME2 NOT NULL CONSTRAINT DF_PORTAL_SECTION_ACCESS_created_at DEFAULT SYSUTCDATETIME(),
    updated_at DATETIME2 NOT NULL CONSTRAINT DF_PORTAL_SECTION_ACCESS_updated_at DEFAULT SYSUTCDATETIME()
  );
END;

/* USER_NOTIFICATION_SETTINGS */
IF OBJECT_ID('PORTAL.USER_NOTIFICATION_SETTINGS','U') IS NULL
BEGIN
  CREATE TABLE PORTAL.USER_NOTIFICATION_SETTINGS (
    id INT IDENTITY(1,1) PRIMARY KEY,
    tenant_id NVARCHAR(50) NOT NULL,
    user_id NVARCHAR(50) NOT NULL,
    notify_on_upload BIT NULL,
    notify_on_alert BIT NULL,
    notify_on_digest BIT NULL,
    ext_attributes NVARCHAR(MAX) NULL,
    created_by NVARCHAR(255) NOT NULL CONSTRAINT DF_PORTAL_USER_NOTIF_created_by DEFAULT('MANUAL'),
    created_at DATETIME2 NOT NULL CONSTRAINT DF_PORTAL_USER_NOTIF_created_at DEFAULT SYSUTCDATETIME(),
    updated_at DATETIME2 NOT NULL CONSTRAINT DF_PORTAL_USER_NOTIF_updated_at DEFAULT SYSUTCDATETIME()
  );
  CREATE INDEX IX_PORTAL_USER_NOTIF_tenant_user ON PORTAL.USER_NOTIFICATION_SETTINGS(tenant_id, user_id);
END;

/* SUBSCRIPTION */
IF OBJECT_ID('PORTAL.SUBSCRIPTION','U') IS NULL
BEGIN
  CREATE TABLE PORTAL.SUBSCRIPTION (
    id INT IDENTITY(1,1) PRIMARY KEY,
    tenant_id NVARCHAR(50) NOT NULL,
    plan_code NVARCHAR(50) NOT NULL,
    status NVARCHAR(50) NOT NULL,
    start_date DATETIME2 NOT NULL,
    end_date DATETIME2 NOT NULL,
    external_payment_id NVARCHAR(100) NULL,
    payment_provider NVARCHAR(50) NULL,
    last_payment_date DATETIME2 NULL,
    ext_attributes NVARCHAR(MAX) NULL,
    created_by NVARCHAR(255) NOT NULL CONSTRAINT DF_PORTAL_SUBSCRIPTION_created_by DEFAULT('MANUAL'),
    created_at DATETIME2 NOT NULL CONSTRAINT DF_PORTAL_SUBSCRIPTION_created_at DEFAULT SYSUTCDATETIME(),
    updated_at DATETIME2 NOT NULL CONSTRAINT DF_PORTAL_SUBSCRIPTION_updated_at DEFAULT SYSUTCDATETIME()
  );
  CREATE INDEX IX_PORTAL_SUBSCRIPTION_tenant ON PORTAL.SUBSCRIPTION(tenant_id);
END;

/* MASKING_METADATA */
IF OBJECT_ID('PORTAL.MASKING_METADATA','U') IS NULL
BEGIN
  CREATE TABLE PORTAL.MASKING_METADATA (
    id INT IDENTITY(1,1) PRIMARY KEY,
    tenant_id NVARCHAR(50) NULL,
    schema_name NVARCHAR(50) NULL,
    table_name NVARCHAR(100) NULL,
    column_name NVARCHAR(100) NULL,
    mask_type NVARCHAR(50) NULL,
    note NVARCHAR(255) NULL,
    ext_attributes NVARCHAR(MAX) NULL,
    created_by NVARCHAR(255) NOT NULL CONSTRAINT DF_PORTAL_MASKING_created_by DEFAULT('MANUAL'),
    created_at DATETIME2 NOT NULL CONSTRAINT DF_PORTAL_MASKING_created_at DEFAULT SYSUTCDATETIME(),
    updated_at DATETIME2 NOT NULL CONSTRAINT DF_PORTAL_MASKING_updated_at DEFAULT SYSUTCDATETIME()
  );
END;

/* RLS_METADATA */
IF OBJECT_ID('PORTAL.RLS_METADATA','U') IS NULL
BEGIN
  CREATE TABLE PORTAL.RLS_METADATA (
    id INT IDENTITY(1,1) PRIMARY KEY,
    tenant_id NVARCHAR(50) NULL,
    schema_name NVARCHAR(50) NULL,
    table_name NVARCHAR(100) NULL,
    column_name NVARCHAR(100) NULL,
    policy_name NVARCHAR(100) NULL,
    predicate_function NVARCHAR(255) NULL,
    note NVARCHAR(255) NULL,
    ext_attributes NVARCHAR(MAX) NULL,
    created_by NVARCHAR(255) NOT NULL CONSTRAINT DF_PORTAL_RLS_created_by DEFAULT('MANUAL'),
    created_at DATETIME2 NOT NULL CONSTRAINT DF_PORTAL_RLS_created_at DEFAULT SYSUTCDATETIME(),
    updated_at DATETIME2 NOT NULL CONSTRAINT DF_PORTAL_RLS_updated_at DEFAULT SYSUTCDATETIME()
  );
END;

