<#
.SYNOPSIS
    Automates semantic enrichment of documentation using Azure OpenAI.

.DESCRIPTION
    Iterates through documentation files (default: .md in Wiki) and uses a configured LLM to:
    1. Generate a 'summary' if missing or placeholder (e.g. 'TODO').
    2. Generate a 'Domande a cui risponde' section if missing.
    3. Update the file status from 'draft' to 'active' if enrichment is successful.

    REQUIRES: 
    - AZURE_OPENAI_ENDPOINT
    - AZURE_OPENAI_KEY
    - AZURE_OPENAI_DEPLOYMENT (default: gpt-4o)

.PARAMETER WikiPath
    Path to the Wiki root directory. Default: "Wiki/EasyWayData.wiki"

.PARAMETER DryRun
    If set, only prints what would happen without modifying files.

.EXAMPLE
    .\agent-enrich-docs.ps1 -WikiPath "Wiki/EasyWayData.wiki" -Verbose
#>
param(
    [string]$WikiPath = "Wiki/EasyWayData.wiki",
    [switch]$DryRun
)

# Configuration
$Endpoint = $env:AZURE_OPENAI_ENDPOINT
$Key = $env:AZURE_OPENAI_KEY
$Deployment = if ($env:AZURE_OPENAI_DEPLOYMENT) { $env:AZURE_OPENAI_DEPLOYMENT } else { "gpt-4o" }
$ApiVersion = "2024-02-15-preview"

# Try loading from local secrets file if Env Vars are missing
$SecretsFile = Join-Path $PSScriptRoot "easyway-secrets.json"
if ((-not $Endpoint -or -not $Key) -and (Test-Path $SecretsFile)) {
    try {
        $secrets = Get-Content $SecretsFile -Raw | ConvertFrom-Json
        if ($secrets.AZURE_OPENAI_ENDPOINT) { $Endpoint = $secrets.AZURE_OPENAI_ENDPOINT }
        if ($secrets.AZURE_OPENAI_KEY) { $Key = $secrets.AZURE_OPENAI_KEY }
        if ($secrets.AZURE_OPENAI_DEPLOYMENT) { $Deployment = $secrets.AZURE_OPENAI_DEPLOYMENT }
        Write-Host " [Config] Loaded credentials from easyway-secrets.json" -ForegroundColor Cyan
    }
    catch {
        Write-Warning "Failed to parse secrets file."
    }
}

if (-not $Endpoint -or -not $Key) {
    Write-Warning "LLM Configuration missing."
    Write-Warning "Please set env vars: AZURE_OPENAI_ENDPOINT and AZURE_OPENAI_KEY"
    Write-Warning "OR create a file '$SecretsFile' with JSON content:"
    Write-Warning '{ "AZURE_OPENAI_ENDPOINT": "...", "AZURE_OPENAI_KEY": "..." }'
    exit 1
}

function Invoke-Llm {
    param([string]$SystemPrompt, [string]$UserPrompt)
    
    $url = "$($Endpoint.TrimEnd('/'))/openai/deployments/$Deployment/chat/completions?api-version=$ApiVersion"
    $headers = @{
        "api-key"      = $Key
        "Content-Type" = "application/json"
    }
    
    $body = @{
        messages    = @(
            @{ role = "system"; content = $SystemPrompt },
            @{ role = "user"; content = $UserPrompt }
        )
        temperature = 0.3
        max_tokens  = 500
    } | ConvertTo-Json -Depth 5 -Compress

    try {
        $response = Invoke-RestMethod -Uri $url -Method Post -Headers $headers -Body $body -ErrorAction Stop
        return $response.choices[0].message.content
    }
    catch {
        Write-Error "LLM Call Failed: $_"
        return $null
    }
}

$files = Get-ChildItem -LiteralPath $WikiPath -Recurse -Filter *.md

foreach ($f in $files) {
    $content = Get-Content $f.FullName -Raw
    $originalContent = $content
    $modified = $false

    # Skip files that are likely templates or autogenerated logs
    if ($f.Name.StartsWith("_") -or $f.FullName -match "logs\\") { continue }

    Write-Host "Processing $($f.Name)..." -NoNewline

    # --- 1. Enrich Summary ---
    # Check if summary is missing, empty, or "TODO"/"Placeholder"
    $hasSummary = $content -match '(?m)^summary:\s*(.+)$'
    $currentSummary = if ($matches) { $matches[1].Trim() } else { $null }
    
    if (-not $currentSummary -or $currentSummary -match 'TODO|Placeholder|Pagina top-level|Una breve descrizione') {
        if ($DryRun) { Write-Host " [Would Enrich Summary]" -ForegroundColor Yellow }
        else {
            Write-Host " [Enriching Summary]" -ForegroundColor Cyan -NoNewline
            
            $sysPrompt = "You are a technical documentation assistant. Write a concise (150 chars max) summary in Italian for the provided markdown document. Focus on the 'WHAT' and 'WHY'. Do not use 'This document describes...' just describe the content directly."
            $newSummary = Invoke-Llm -SystemPrompt $sysPrompt -UserPrompt $content

            if ($newSummary) {
                $newSummary = $newSummary.Trim().Replace("`"", "'") # Sanitize quotes
                if ($hasSummary) {
                    $content = $content -replace '(?m)^summary:.*$', "summary: $newSummary"
                }
                else {
                    $content = $content -replace '(?m)^---(\r?\n)', "--`${1}summary: $newSummary`${1}"
                }
                $modified = $true
            }
        }
    }

    # --- 2. Enrich Questions (Domande a cui risponde) ---
    if ($content -notmatch '(?i)##\s*Domande a cui risponde') {
        if ($DryRun) { Write-Host " [Would Add Questions]" -ForegroundColor Yellow }
        else {
            Write-Host " [Adding Questions]" -ForegroundColor Cyan -NoNewline
            
            $sysPrompt = "You are a technical documentation assistant. Generate 3 specific questions in Italian that the provided document answers. Format as a markdown numbered list. Do not include the header, just the list."
            $questions = Invoke-Llm -SystemPrompt $sysPrompt -UserPrompt $content

            if ($questions) {
                # Append to end of file
                $content += "`r`n`r`n## Domande a cui risponde`r`n$questions"
                $modified = $true
            }
        }
    }

    # --- 3. Update Status and Timestamp ---
    if ($modified) {
        # Update status to active if it was draft
        if ($content -match '(?m)^status:\s*draft') {
            $content = $content -replace '(?m)^status:\s*draft', "status: active"
        }
        # Update timestamp
        $today = Get-Date -Format "yyyy-MM-dd"
        if ($content -match '(?m)^updated:.*') {
            $content = $content -replace '(?m)^updated:.*', "updated: '$today'"
        }
        else {
            # Add updated if missing (after title ideally, but anywhere in frontmatter works)
            $content = $content -replace '(?m)^---(\r?\n)', "--`${1}updated: '$today'`${1}"
        }

        # Save File
        Set-Content -Path $f.FullName -Value $content -Encoding utf8
        Write-Host " [SAVED]" -ForegroundColor Green
    }
    else {
        Write-Host " [OK]" -ForegroundColor Green
    }
}
