<#
.SYNOPSIS
  Generic L3 Planner: reads backlog.json + platform-config.json, produces execution_plan.json.
.DESCRIPTION
  Platform-agnostic replacement for ado-plan-apply.ps1.
  Acts as L3 Validator: reads the backlog, queries the target platform adapter
  for existing items (dedup), and produces a deterministic execution plan
  for the L1 Executor (platform-apply.ps1).

  See: EASYWAY_AGENTIC_SDLC_MASTER.md §11 (Platform Adapter Pattern)
  See: docs/AGENTIC_ARCHITECTURE_ENTERPRISE_PRD.md §19 (Nomenclatura)
.NOTES
  Part of Phase 9 Feature 17 — Platform Adapter SDK.
  Replaces: ado-plan-apply.ps1 (which now delegates here).
#>

Param(
    [Parameter(Mandatory = $true)]
    [string]$BacklogPath,

    [Parameter(Mandatory = $false)]
    [string]$OutputPath = 'out/execution_plan.json',

    [Parameter(Mandatory = $false)]
    [string]$ConfigPath
)

$ErrorActionPreference = 'Stop'

# ── Resolve config path ──────────────────────────────────────────────────────
$repoRoot = (git rev-parse --show-toplevel 2>$null)
if (-not $repoRoot) { $repoRoot = $PWD.Path }

if (-not $ConfigPath) {
    $ConfigPath = Join-Path $repoRoot 'config' 'platform-config.json'
}

# ── Import core modules ──────────────────────────────────────────────────────
$coreDir = Join-Path $repoRoot 'scripts' 'pwsh' 'core'
$adapterDir = Join-Path $coreDir 'adapters'

Import-Module (Join-Path $coreDir 'PlatformCommon.psm1') -Force
Import-Module (Join-Path $adapterDir 'IPlatformAdapter.psm1') -Force

# ── Load config ───────────────────────────────────────────────────────────────
$config = Read-PlatformConfig -ConfigPath $ConfigPath
Write-Host "L3 Planner: Platform = $($config.platform) ($($config.displayName))"

# ── Resolve token & create adapter ────────────────────────────────────────────
$token = Resolve-PlatformToken -Config $config -AgentId 'agent_planner' -RepoRoot $repoRoot

$adapter = $null
if ($token) {
    $headers = Get-AuthHeader -Config $config -Token $token
    $adapter = New-PlatformAdapter -Config $config -Headers $headers
}
else {
    Write-Warning "Platform token not available (RBAC_DENY or unavailable). Running in Blind-Planner mode."
}

# ── Load backlog ──────────────────────────────────────────────────────────────
$backlog = Read-BacklogFile -Path $BacklogPath
$prdId = $backlog.prdId

Write-Host "L3 Validation: Planning execution for PRD ID [$prdId]..."

# ── Build execution plan ──────────────────────────────────────────────────────
$executionPlan = @()
$globalTags = @($config.tags.autoGenerated, "PRD:$prdId")
$virtualIdCounter = -1

# Resolve hierarchy levels from config
$lvl1 = Get-HierarchyLevel -Config $config -Level 1   # Epic
$lvl2 = Get-HierarchyLevel -Config $config -Level 2   # Feature
$lvl3 = Get-HierarchyLevel -Config $config -Level 3   # PBI

foreach ($epic in $backlog.epics) {
    $epic.title = Format-WorkItemTitle -Title $epic.title -Prefix $lvl1.prefix
    $epicId = $null

    if ($adapter) {
        $epicId = $adapter.QueryWorkItemByTitle($lvl1.type, $epic.title, $prdId)
    }

    if (-not $epicId) {
        $epicId = $virtualIdCounter--
        $executionPlan += [ordered]@{
            action        = 'CREATE'
            type          = $lvl1.type
            tempId        = $epicId
            title         = $epic.title
            description   = $epic.description
            areaPath      = $config.paths.areaPath
            iterationPath = $config.paths.iterationPath
            tags          = $globalTags
            parentId      = $null
        }
    }
    else {
        $executionPlan += [ordered]@{ action = 'EXISTING'; type = $lvl1.type; id = $epicId; title = $epic.title }
    }

    foreach ($feature in $epic.features) {
        $feature.title = Format-WorkItemTitle -Title $feature.title -Prefix $lvl2.prefix
        $featureId = $null

        if ($adapter) {
            $featureId = $adapter.QueryWorkItemByTitle($lvl2.type, $feature.title, $prdId)
        }

        if (-not $featureId) {
            $featureId = $virtualIdCounter--
            $executionPlan += [ordered]@{
                action        = 'CREATE'
                type          = $lvl2.type
                tempId        = $featureId
                title         = $feature.title
                description   = $feature.description
                areaPath      = $config.paths.areaPath
                iterationPath = $config.paths.iterationPath
                tags          = $globalTags
                parentId      = $epicId
            }
        }
        else {
            $executionPlan += [ordered]@{ action = 'EXISTING'; type = $lvl2.type; id = $featureId; title = $feature.title }
        }

        if ($feature.pbis) {
            foreach ($pbi in $feature.pbis) {
                $pbi.title = Format-WorkItemTitle -Title $pbi.title -Prefix $lvl3.prefix
                $pbiId = $null

                if ($adapter) {
                    $pbiId = $adapter.QueryWorkItemByTitle($lvl3.type, $pbi.title, $prdId)
                }

                if (-not $pbiId) {
                    $pbiId = $virtualIdCounter--
                    $executionPlan += [ordered]@{
                        action             = 'CREATE'
                        type               = $lvl3.type
                        tempId             = $pbiId
                        title              = $pbi.title
                        description        = ''
                        acceptanceCriteria = $pbi.acceptanceCriteria
                        areaPath           = $config.paths.areaPath
                        iterationPath      = $config.paths.iterationPath
                        tags               = $globalTags
                        parentId           = $featureId
                    }
                }
                else {
                    $executionPlan += [ordered]@{ action = 'EXISTING'; type = $lvl3.type; id = $pbiId; title = $pbi.title }
                }
            }
        }
    }
}

# ── Write execution plan ──────────────────────────────────────────────────────
$outDir = [IO.Path]::GetDirectoryName($OutputPath)
if ($outDir -and -not (Test-Path $outDir)) { New-Item -ItemType Directory -Force -Path $outDir | Out-Null }

$planDoc = [ordered]@{
    prdId         = $prdId
    platform      = $config.platform
    baseUrl       = $config.connection.baseUrl
    project       = $config.connection.project
    itemsToCreate = @($executionPlan | Where-Object action -eq 'CREATE').Count
    plan          = $executionPlan
}

$planDoc | ConvertTo-Json -Depth 30 -Compress | Out-File -FilePath $OutputPath -Encoding utf8
Write-Host "L3 Validation Complete. Plan saved to $OutputPath ($($planDoc.itemsToCreate) items to create)"
