#!/usr/bin/env pwsh
<#
.SYNOPSIS
    Sync the Platform Operational Knowledge section of .cursorrules from the Wiki source.

.DESCRIPTION
    Single source of truth: Wiki/EasyWayData.wiki/agents/platform-operational-memory.md
    Targets:
      - .cursorrules   (section between AUTO-SYNC-START and AUTO-SYNC-END markers)

    The script extracts the human-readable body of the wiki (strips YAML frontmatter),
    converts it to a compact reference block, and replaces the marked section.

    Run manually:     pwsh scripts/pwsh/Sync-PlatformMemory.ps1
    Auto (hook):      triggered by pre-commit when the wiki source file is staged

.PARAMETER WikiFile
    Path to the platform-operational-memory wiki file (relative to repo root).

.PARAMETER CursorRulesFile
    Path to the .cursorrules file.

.PARAMETER DryRun
    Preview the generated content without writing to disk.

.EXAMPLE
    pwsh scripts/pwsh/Sync-PlatformMemory.ps1
    pwsh scripts/pwsh/Sync-PlatformMemory.ps1 -DryRun
#>
param(
    [string] $WikiFile       = 'Wiki/EasyWayData.wiki/agents/platform-operational-memory.md',
    [string] $CursorRulesFile = '.cursorrules',
    [switch] $DryRun
)

$ErrorActionPreference = 'Stop'

# ---------------------------------------------------------------------------
# 0. Resolve repo root (script lives in scripts/pwsh/, root is two levels up)
# ---------------------------------------------------------------------------
$repoRoot = Split-Path (Split-Path $PSScriptRoot -Parent) -Parent
$wikiPath   = Join-Path $repoRoot $WikiFile
$cursorPath = Join-Path $repoRoot $CursorRulesFile

if (-not (Test-Path $wikiPath)) {
    Write-Error "Wiki source not found: $wikiPath"
    exit 1
}
if (-not (Test-Path $cursorPath)) {
    Write-Error ".cursorrules not found: $cursorPath"
    exit 1
}

Write-Host "[Sync-PlatformMemory] Source  : $WikiFile" -ForegroundColor Cyan
Write-Host "[Sync-PlatformMemory] Target  : $CursorRulesFile" -ForegroundColor Cyan

# ---------------------------------------------------------------------------
# 1. Read and parse the wiki file
# ---------------------------------------------------------------------------
$wikiRaw   = Get-Content $wikiPath -Raw -Encoding UTF8
$wikiLines = Get-Content $wikiPath -Encoding UTF8

# Strip YAML frontmatter (lines between first and second '---')
$inFrontmatter = $false
$frontmatterDone = $false
$bodyLines = [System.Collections.Generic.List[string]]::new()

for ($i = 0; $i -lt $wikiLines.Count; $i++) {
    $line = $wikiLines[$i]
    if ($i -eq 0 -and $line -eq '---') {
        $inFrontmatter = $true
        continue
    }
    if ($inFrontmatter -and $line -eq '---') {
        $inFrontmatter = $false
        $frontmatterDone = $true
        continue
    }
    if (-not $inFrontmatter) {
        $bodyLines.Add($line)
    }
}

$wikiBody = ($bodyLines -join "`n").TrimStart()

# ---------------------------------------------------------------------------
# 2. Build the AUTO-SYNC block content
# ---------------------------------------------------------------------------
$timestamp = (Get-Date -Format 'yyyy-MM-ddTHH:mm:ssZ')

$syncBlock = @"
# AUTO-SYNC-START: Regenerated by scripts/pwsh/Sync-PlatformMemory.ps1
# Source: $WikiFile
# Last sync: $timestamp
# To refresh manually: pwsh scripts/pwsh/Sync-PlatformMemory.ps1
# Runs automatically on pre-commit when the wiki source file is staged.

$wikiBody

# AUTO-SYNC-END
"@

# ---------------------------------------------------------------------------
# 3. Replace the marked section in .cursorrules
# ---------------------------------------------------------------------------
$cursorContent = Get-Content $cursorPath -Raw -Encoding UTF8

$startMarker = '# AUTO-SYNC-START'
$endMarker   = '# AUTO-SYNC-END'

$startIdx = $cursorContent.IndexOf($startMarker)
$endIdx   = $cursorContent.IndexOf($endMarker)

if ($startIdx -lt 0 -or $endIdx -lt 0) {
    Write-Error ".cursorrules is missing AUTO-SYNC markers. Add '# AUTO-SYNC-START' and '# AUTO-SYNC-END' to the file."
    exit 1
}

# Everything before the start marker
$before = $cursorContent.Substring(0, $startIdx)

# Everything after the end marker (including the newline after it)
$afterStart = $endIdx + $endMarker.Length
$after = if ($afterStart -lt $cursorContent.Length) {
    $cursorContent.Substring($afterStart)
} else { '' }

$newContent = $before + $syncBlock + $after

# ---------------------------------------------------------------------------
# 4. Write (or preview in DryRun)
# ---------------------------------------------------------------------------
if ($DryRun) {
    Write-Host "`n[DryRun] Generated AUTO-SYNC block ($($syncBlock.Length) chars):" -ForegroundColor Yellow
    Write-Host "--- PREVIEW (first 80 lines) ---" -ForegroundColor DarkGray
    $syncBlock -split "`n" | Select-Object -First 80 | ForEach-Object { Write-Host "  $_" -ForegroundColor DarkGray }
    Write-Host "--- END PREVIEW ---" -ForegroundColor DarkGray
    Write-Host "[DryRun] No files written." -ForegroundColor Yellow
    exit 0
}

# Write with UTF-8 no BOM (same encoding as the existing file)
[System.IO.File]::WriteAllText($cursorPath, $newContent, [System.Text.UTF8Encoding]::new($false))

Write-Host "[Sync-PlatformMemory] .cursorrules updated successfully." -ForegroundColor Green
Write-Host "[Sync-PlatformMemory] AUTO-SYNC block: $($syncBlock.Length) chars from wiki ($($wikiBody.Length) chars body)." -ForegroundColor Green
