/* V10 — RLS policy on PORTAL.CONFIGURATION (disabled by default) */
GO

IF NOT EXISTS (SELECT 1 FROM sys.security_policies WHERE name = 'RLS_TENANT_POLICY_CONFIGURATION')
BEGIN
  CREATE SECURITY POLICY PORTAL.RLS_TENANT_POLICY_CONFIGURATION
  ADD FILTER PREDICATE PORTAL.fn_rls_tenant_filter(tenant_id) ON PORTAL.CONFIGURATION
  WITH (STATE = OFF);
END;
GO

/* To enable: ALTER SECURITY POLICY PORTAL.RLS_TENANT_POLICY_CONFIGURATION WITH (STATE=ON); */

