/* V2 — Core sequences for NDG codes (numeric part) */

/* Tenant */
IF NOT EXISTS (
  SELECT 1 FROM sys.sequences WHERE name = 'SEQ_TENANT_ID' AND SCHEMA_NAME(schema_id)='PORTAL'
)
BEGIN
  CREATE SEQUENCE PORTAL.SEQ_TENANT_ID AS BIGINT START WITH 1000 INCREMENT BY 1;
END;

IF NOT EXISTS (
  SELECT 1 FROM sys.sequences WHERE name = 'SEQ_TENANT_ID_DEBUG' AND SCHEMA_NAME(schema_id)='PORTAL'
)
BEGIN
  CREATE SEQUENCE PORTAL.SEQ_TENANT_ID_DEBUG AS BIGINT START WITH 1 INCREMENT BY 1;
END;

/* Users */
IF NOT EXISTS (
  SELECT 1 FROM sys.sequences WHERE name = 'SEQ_USER_ID' AND SCHEMA_NAME(schema_id)='PORTAL'
)
BEGIN
  CREATE SEQUENCE PORTAL.SEQ_USER_ID AS BIGINT START WITH 1000 INCREMENT BY 1;
END;

IF NOT EXISTS (
  SELECT 1 FROM sys.sequences WHERE name = 'SEQ_USER_ID_DEBUG' AND SCHEMA_NAME(schema_id)='PORTAL'
)
BEGIN
  CREATE SEQUENCE PORTAL.SEQ_USER_ID_DEBUG AS BIGINT START WITH 1 INCREMENT BY 1;
END;

