Param(
  [string]$ApiPath = "EasyWay-DataPortal/easyway-portal-api",
  [string]$TenantId = "YOUR_TENANT_ID",
  [string]$AuthClientId = "YOUR_MSAL_CLIENT_ID",
  [string]$DbConnString = "Server=tcp:localhost,1433;Database=EASYWAY_DEV;User Id=sa;Password=YourStrong!Passw0rd;Encrypt=false",
  [string]$DefaultBusinessTenant = "tenant01"
)

$ErrorActionPreference = 'Stop'
$envFile = Join-Path $ApiPath ".env.local"

@"
# Generated by setup-env.ps1
LOG_LEVEL=debug
AUTH_ISSUER=https://login.microsoftonline.com/$TenantId/v2.0
AUTH_JWKS_URI=https://login.microsoftonline.com/$TenantId/discovery/v2.0/keys
AUTH_AUDIENCE=api://your-app-id
TENANT_CLAIM=ew_tenant_id
AUTH_CLIENT_ID=$AuthClientId
AUTH_TENANT_ID=$TenantId
DB_CONN_STRING=$DbConnString
AZURE_STORAGE_CONNECTION_STRING=UseDevelopmentStorage=true
BRANDING_CONTAINER=portal-assets
BRANDING_PREFIX=config
DEFAULT_TENANT_ID=$DefaultBusinessTenant
RLS_CONTEXT_ENABLED=true
"@ | Set-Content -Encoding UTF8 $envFile

Write-Host "Wrote $envFile" -ForegroundColor Green

