#Requires -Version 5.1
<#
.SYNOPSIS
    Agent_Discovery L2 Runner — PRD generation and validation.
.DESCRIPTION
    L2 Router/Orchestrator for the Discovery phase. Receives a requirement
    (text file or inline), enriches it via RAG search on the Wiki/repo,
    and produces a structured PRD draft ready for human review.

    Actions:
      discovery:generate-prd  — Generate PRD from requirement
      discovery:validate-prd  — Validate existing PRD for completeness

    See: EASYWAY_AGENTIC_SDLC_MASTER.md §4 (Discovery Phase)
    See: agents/agent_discovery/PROMPTS.md
.NOTES
    Part of Phase 9 — Agent Formalization.
    Level: L2 (Router/Orchestrator — uses L1 skills, applies domain logic)
#>

Param(
    [Parameter(Mandatory = $false)]
    [ValidateSet('generate', 'validate')]
    [string]$Action = 'generate',

    [Parameter(Mandatory = $true)]
    [string]$InputPath,

    [Parameter(Mandatory = $false)]
    [string]$OutputPath = 'out/prd-draft.md'
)

$ErrorActionPreference = 'Stop'

# ── Resolve paths ─────────────────────────────────────────────────────────────
$repoRoot = (git rev-parse --show-toplevel 2>$null)
if (-not $repoRoot) { $repoRoot = $PWD.Path }

$coreDir = Join-Path $repoRoot 'scripts' 'pwsh' 'core'

# ── Import skills ─────────────────────────────────────────────────────────────
Import-Module (Join-Path $coreDir 'TelemetryLogger.psm1') -Force

# Initialize telemetry
Initialize-TelemetryLogger -TraceId "discovery-$(Get-Date -Format 'yyyyMMdd-HHmm')"

# ── Load requirement ─────────────────────────────────────────────────────────
Write-Host "[Agent_Discovery] L2 Runner — Action: $Action"

if (-not (Test-Path $InputPath)) {
    throw "[Agent_Discovery] Input file not found: $InputPath"
}
$requirement = Get-Content $InputPath -Raw -Encoding UTF8

Write-Host "[Agent_Discovery] Loaded requirement ($($requirement.Length) chars)"

# ── Action: Generate PRD ──────────────────────────────────────────────────────
if ($Action -eq 'generate') {

    $prdContent = Measure-AgentAction -AgentId 'agent_discovery' -AgentLevel 'L2' -Action 'discovery:generate-prd' -ScriptBlock {

        # 1. Check for RAG skill availability
        $ragSkill = Join-Path $repoRoot 'agents' 'skills' 'retrieval' 'Invoke-RAGSearch.ps1'
        $ragContext = ''
        if (Test-Path $ragSkill) {
            Write-Host "  > RAG: Searching Wiki for context..."
            try {
                # Extract key terms from requirement for RAG query
                $terms = ($requirement -split '\s+' | Where-Object { $_.Length -gt 5 } | Select-Object -First 10) -join ' '
                $ragContext = & $ragSkill -Query $terms -TopK 5 2>$null
                if ($ragContext) {
                    Write-Host "  > RAG: Found $($ragContext.Length) chars of context"
                }
            }
            catch {
                Write-Warning "  > RAG search failed (non-blocking): $_"
            }
        }
        else {
            Write-Host "  > RAG: Skill not available, proceeding without Wiki context"
        }

        # 2. Load PRD template
        $templatePath = Join-Path $repoRoot 'docs' 'templates' 'PRD_AGENTIC_SAMPLE.md'
        $template = ''
        if (Test-Path $templatePath) {
            $template = Get-Content $templatePath -Raw -Encoding UTF8
            Write-Host "  > Template loaded ($($template.Length) chars)"
        }

        # 3. Build PRD structure
        $prd = @"
# PRD Draft — $(Get-Date -Format 'yyyy-MM-dd')

> **Generated by**: agent_discovery (L2)
> **Status**: DRAFT — requires human review
> **Confidence**: Medium (automated generation)

---

## 1. Requisito Originale

$requirement

---

## 2. Contesto RAG (Evidenze dal Wiki)

$(if ($ragContext) { $ragContext } else { '_Nessun contesto RAG disponibile. Validare manualmente._' })

---

## 3. Obiettivo Business

_[Da completare sulla base del requisito sopra]_

## 4. Scope

### In Scope
- _[Elencare funzionalita incluse]_

### Out of Scope
- _[Elencare espliciti esclusioni]_

## 5. Fonti Dati e Mapping

| Sorgente | Tipo | Tabella/Endpoint | Note |
|---|---|---|---|
| _[Da compilare]_ | | | |

## 6. Data Quality

| Controllo | Soglia | Azione su failure |
|---|---|---|
| _[Da compilare]_ | | |

## 7. Impatti Tecnici

- **API**: _[Nuovi endpoint o modifiche]_
- **Database**: _[Schema changes]_
- **Frontend**: _[UI changes]_
- **ETL/Pipeline**: _[Nuovi flussi]_

## 8. Sicurezza / RBAC / Audit

- _[Requisiti accesso]_

## 9. Rischi e Mitigazioni

| Rischio | Probabilita | Impatto | Mitigazione |
|---|---|---|---|
| _[Da compilare]_ | | | |

## 10. Acceptance Criteria

- [ ] _[Criterio 1]_
- [ ] _[Criterio 2]_

## 11. Checklist: Ready for Backlog Decomposition

- [ ] Obiettivo business chiaro
- [ ] Scope definito (in/out)
- [ ] Fonti dati identificate
- [ ] Controlli DQ definiti
- [ ] Acceptance criteria verificabili

**Ready**: ⬜ YES / ⬜ NO — _Motivazione: [...]_

---

_Prossimo step: `agent_backlog_planner backlog:whatif -prdPath <this-file>`_
"@
        return $prd
    }

    # Write output
    $outDir = [IO.Path]::GetDirectoryName($OutputPath)
    if ($outDir -and -not (Test-Path $outDir)) { New-Item -ItemType Directory -Force -Path $outDir | Out-Null }
    $prdContent | Out-File -FilePath $OutputPath -Encoding utf8

    Write-Host "[Agent_Discovery] PRD draft saved to: $OutputPath"
    Write-TelemetryEvent -AgentId 'agent_discovery' -AgentLevel 'L2' -Action 'discovery:prd-saved' -Outcome 'success' `
        -Details @{ outputPath = $OutputPath; chars = $prdContent.Length }
}

# ── Action: Validate PRD ─────────────────────────────────────────────────────
if ($Action -eq 'validate') {

    $null = Measure-AgentAction -AgentId 'agent_discovery' -AgentLevel 'L2' -Action 'discovery:validate-prd' -ScriptBlock {

        $requiredSections = @(
            'Obiettivo Business',
            'Scope',
            'Fonti Dati',
            'Data Quality',
            'Acceptance Criteria'
        )

        $missing = @()
        foreach ($section in $requiredSections) {
            if ($requirement -notmatch [regex]::Escape($section)) {
                $missing += $section
            }
        }

        if ($missing.Count -eq 0) {
            Write-Host "[Agent_Discovery] ✅ PRD validation PASSED — all required sections present"
        }
        else {
            Write-Warning "[Agent_Discovery] ⚠️ PRD validation: $($missing.Count) missing section(s):"
            $missing | ForEach-Object { Write-Warning "  - $_" }
        }

        # Check for placeholder markers
        $placeholders = ([regex]::Matches($requirement, '\[Da compilare\]|\[Da completare\]|_\[.*?\]_')).Count
        if ($placeholders -gt 0) {
            Write-Warning "[Agent_Discovery] ⚠️ Found $placeholders placeholder(s) — fill before backlog decomposition"
        }
    }
}

Write-Host "[Agent_Discovery] Done."
