#Requires -Modules Pester
<#
.SYNOPSIS
    Pester tests for PlatformCommon.psm1 (Pester v3 compatible).
.NOTES
    Run: Invoke-Pester -Path "scripts/pwsh/core/PlatformCommon.Tests.ps1" -Verbose
#>

Import-Module "$PSScriptRoot/PlatformCommon.psm1" -Force

Describe 'Read-PlatformConfig' {
    $validConfig = @{
        platform          = 'ado'
        displayName       = 'Test ADO Config'
        connection        = @{
            baseUrl    = 'https://dev.azure.com/TestOrg'
            project    = 'TestProject'
            apiVersion = '7.0'
        }
        auth              = @{
            method       = 'pat'
            envVariable  = 'TEST_PAT'
            headerScheme = 'Basic'
        }
        workItemHierarchy = @{
            processTemplate     = 'Scrum'
            chain               = @(
                @{ level = 1; type = 'Epic'; prefix = '[Epic]' }
                @{ level = 2; type = 'Feature'; prefix = '[Feature]' }
                @{ level = 3; type = 'Product Backlog Item'; prefix = '[PBI]' }
            )
            parentChildLinkType = 'System.LinkTypes.Hierarchy-Reverse'
        }
        paths             = @{ areaPath = '\TestProject'; iterationPath = '' }
        tags              = @{ autoGenerated = 'AutoPRD'; aiGenerated = 'AI-Generated' }
    }
    $tempDir = Join-Path ([IO.Path]::GetTempPath()) "pester-platform-$(Get-Random)"
    New-Item -ItemType Directory -Path $tempDir -Force | Out-Null

    It 'Should load a valid config file' {
        $configPath = Join-Path $tempDir 'valid.json'
        $validConfig | ConvertTo-Json -Depth 10 | Out-File $configPath -Encoding utf8

        $result = Read-PlatformConfig -ConfigPath $configPath
        $result.platform | Should Be 'ado'
        $result.connection.project | Should Be 'TestProject'
        $result.workItemHierarchy.chain.Count | Should Be 3
    }

    It 'Should throw when file does not exist' {
        $threw = $false
        try { Read-PlatformConfig -ConfigPath 'C:\nonexistent\config.json' } catch { $threw = $true }
        $threw | Should Be $true
    }

    It 'Should throw on unknown platform' {
        $badConfig = $validConfig.Clone()
        $badConfig.platform = 'invalid_platform'
        $configPath = Join-Path $tempDir 'bad-platform.json'
        $badConfig | ConvertTo-Json -Depth 10 | Out-File $configPath -Encoding utf8

        $threw = $false
        try { Read-PlatformConfig -ConfigPath $configPath } catch { $threw = $true }
        $threw | Should Be $true
    }

    It 'Should throw when required field missing' {
        $badConfig = @{ platform = 'ado' }
        $configPath = Join-Path $tempDir 'missing-fields.json'
        $badConfig | ConvertTo-Json -Depth 10 | Out-File $configPath -Encoding utf8

        $threw = $false
        try { Read-PlatformConfig -ConfigPath $configPath } catch { $threw = $true }
        $threw | Should Be $true
    }

    It 'Should accept all 6 valid platform values' {
        foreach ($plat in @('ado', 'github', 'jira', 'forgejo', 'businessmap', 'witboost')) {
            $cfg = $validConfig.Clone()
            $cfg.platform = $plat
            $configPath = Join-Path $tempDir "platform-$plat.json"
            $cfg | ConvertTo-Json -Depth 10 | Out-File $configPath -Encoding utf8

            $result = Read-PlatformConfig -ConfigPath $configPath
            $result.platform | Should Be $plat
        }
    }

    Remove-Item -Recurse -Force $tempDir -ErrorAction SilentlyContinue
}

Describe 'Get-AuthHeader' {
    It 'Should build Basic auth header' {
        $config = [PSCustomObject]@{ auth = [PSCustomObject]@{ headerScheme = 'Basic' } }
        $headers = Get-AuthHeader -Config $config -Token 'test-pat'
        $headers.Authorization | Should BeLike 'Basic *'
    }

    It 'Should build Bearer auth header' {
        $config = [PSCustomObject]@{ auth = [PSCustomObject]@{ headerScheme = 'Bearer' } }
        $headers = Get-AuthHeader -Config $config -Token 'test-token'
        $headers.Authorization | Should Be 'Bearer test-token'
    }

    It 'Should build token auth header' {
        $config = [PSCustomObject]@{ auth = [PSCustomObject]@{ headerScheme = 'token' } }
        $headers = Get-AuthHeader -Config $config -Token 'ghp_xxx'
        $headers.Authorization | Should Be 'token ghp_xxx'
    }

    It 'Should default to Bearer when headerScheme is missing' {
        $config = [PSCustomObject]@{ auth = [PSCustomObject]@{} }
        $headers = Get-AuthHeader -Config $config -Token 'default-token'
        $headers.Authorization | Should Be 'Bearer default-token'
    }
}

Describe 'Format-WorkItemTitle' {
    It 'Should add prefix when absent' {
        $result = Format-WorkItemTitle -Title 'My Epic' -Prefix '[Epic]'
        $result | Should Be '[Epic] My Epic'
    }

    It 'Should NOT duplicate prefix when already present' {
        $result = Format-WorkItemTitle -Title '[Epic] My Epic' -Prefix '[Epic]'
        $result | Should Be '[Epic] My Epic'
    }

    It 'Should trim whitespace' {
        $result = Format-WorkItemTitle -Title '  My Feature  ' -Prefix '[Feature]'
        $result | Should Be '[Feature] My Feature'
    }

    It 'Should be case-insensitive on prefix check' {
        $result = Format-WorkItemTitle -Title '[EPIC] Existing' -Prefix '[Epic]'
        $result | Should Be '[EPIC] Existing'
    }
}

Describe 'Get-HierarchyLevel' {
    $config = [PSCustomObject]@{
        workItemHierarchy = [PSCustomObject]@{
            chain = @(
                [PSCustomObject]@{ level = 1; type = 'Epic'; prefix = '[Epic]' }
                [PSCustomObject]@{ level = 2; type = 'Feature'; prefix = '[Feature]' }
                [PSCustomObject]@{ level = 3; type = 'PBI'; prefix = '[PBI]' }
            )
        }
    }

    It 'Should resolve level 1 to Epic' {
        $entry = Get-HierarchyLevel -Config $config -Level 1
        $entry.type | Should Be 'Epic'
        $entry.prefix | Should Be '[Epic]'
    }

    It 'Should resolve level 2 to Feature' {
        $entry = Get-HierarchyLevel -Config $config -Level 2
        $entry.type | Should Be 'Feature'
    }

    It 'Should throw on invalid level' {
        $threw = $false
        try { Get-HierarchyLevel -Config $config -Level 99 } catch { $threw = $true }
        $threw | Should Be $true
    }
}

Describe 'Join-PlatformUrl' {
    It 'Should build correct URL with encoded project name' {
        $config = [PSCustomObject]@{
            connection = [PSCustomObject]@{
                baseUrl = 'https://dev.azure.com/TestOrg'
                project = 'My Project'
            }
        }
        $result = Join-PlatformUrl -Config $config -PathAndQuery '/_apis/wit/wiql?api-version=7.0'
        $result | Should Be 'https://dev.azure.com/TestOrg/My%20Project/_apis/wit/wiql?api-version=7.0'
    }

    It 'Should handle trailing slash in baseUrl' {
        $config = [PSCustomObject]@{
            connection = [PSCustomObject]@{
                baseUrl = 'https://api.github.com/'
                project = 'my-repo'
            }
        }
        $result = Join-PlatformUrl -Config $config -PathAndQuery '/issues'
        $result | Should Be 'https://api.github.com/my-repo/issues'
    }
}
